# Generated by Django 6.0.2 on 2026-02-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_question_scorehistory_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=5, help_text='Time limit in minutes'),
        ),
    ]
