# Generated by Django 6.0.2 on 2026-02-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_exam_mode',
            field=models.BooleanField(default=False),
        ),
    ]
